[package]
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]
name = "csv-aggregator"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
clap = "2.29.0"
csv = "1.0.0-beta.5"
failure = "0.1.1"
glob = "0.2.11"
rayon = "0.9.0"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_yaml = "0.7.3"
