[package]
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]
name = "csv-aggregator"
version = "0.1.0"

[dependencies]
clap = "2.29.0"
csv = "0.15.0"
failure = "0.1.1"
glob = "0.2.11"
serde = "1.0.24"
serde_derive = "1.0.24"
serde_yaml = "0.7.3"
